In [2]:
#creating numpy array
import numpy as np

arr1 = np.array([1,2,3,4]) #array with list
print(f" 1D array: {arr1} ")

arr2 = np.array([[1,2,3], [7,8,4]])
print(f" 2D array: {arr2} ")

print(f"type of arr1 -> {type(arr1)}")
print(f"type of arr2 -> {type(arr2)}")
print(f"shape of arr1 -> {arr1.shape}")

 1D array: [1 2 3 4] 
 2D array: [[1 2 3]
 [7 8 4]] 
type of arr1 -> <class 'numpy.ndarray'>
type of arr2 -> <class 'numpy.ndarray'>
shape of arr1 -> (4,)


In [17]:
#create array with elements 0
arr1 = np.zeros((3,3))
print (arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#array with elements 1 with 2 row 3 columns
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
#array with element full of (number)
arr3 = np.full((3,2), 5)
print(arr3)

[[5 5]
 [5 5]
 [5 5]]


In [21]:
#identity matrix of size (num)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
#in range we want array with adding number of 2
np.arange(1,10, 2) # o/p 1+2, 3+2,..

array([1, 3, 5, 7, 9])

In [23]:
#equi spaced value in range of(2,10) , total elemnts with 5
np.linspace(2,10, 5)

array([ 2.,  4.,  6.,  8., 10.])

## Array Properties

In [24]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [25]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [28]:
print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


## Changing Data Types

In [38]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70,80,90], [2,3,5]], dtype=np.float64)  # Explicit type)

In [39]:
arr.dtype

dtype('float64')

## Reshaping and Flattening Arrays

In [40]:
arr.shape

(4, 3)

In [41]:
arr

array([[10., 20., 30.],
       [40., 50., 60.],
       [70., 80., 90.],
       [ 2.,  3.,  5.]])

In [42]:
arr.reshape(2,6) # shape such that with row 2 and column with 6

array([[10., 20., 30., 40., 50., 60.],
       [70., 80., 90.,  2.,  3.,  5.]])

In [44]:
arr.flatten() #convert it into 1d array

array([10., 20., 30., 40., 50., 60., 70., 80., 90.,  2.,  3.,  5.])