In [6]:
import numpy as np
arr = np.array([[2,4,6], [8,12,10], [8,4,5]])

In [7]:
arr

array([[ 2,  4,  6],
       [ 8, 12, 10],
       [ 8,  4,  5]])

In [13]:
flat = arr.flatten()

In [14]:
flat

array([ 2,  4,  6,  8, 12, 10,  8,  4,  5])

# indexing

In [15]:
flat[0]

np.int64(2)

In [16]:
flat[-1] #last elemnt

np.int64(5)

## Slicing

In [17]:
flat[3:7]

array([ 8, 12, 10,  8])

In [18]:
flat[2:] #same as elements from index 2 to length of arr

array([ 6,  8, 12, 10,  8,  4,  5])

In [19]:
flat[: 5]

array([ 2,  4,  6,  8, 12])

In [20]:
flat[:: 3] #every 3rd element 

array([2, 8, 8])

In [21]:
#let say i create another arr of arr2
arr2 = flat[2:5]
print(arr2)

[ 6  8 12]


In [24]:
arr2[1] = 23233 #change the value at index 1st that is 8
print(arr2)

[    6 23233    12]


In [28]:
#same element is changed in the arr flat , if you don't want to change then take copy of the 2nd arr
#-> arr2 = flat[2:5].copy()
flat

array([    2,     4,     6, 23233,    12,    10,     8,     4,     5])

## Fancy Indexing

In [38]:
#Fancy indexing means using lists or arrays of indices to access multiple elements at once.

arr3 = np.array([1,2,3,4,5,6,7,8,9,10])
idx = [0,2,4,6,8] #index to select
print(arr3[idx])

[1 3 5 7 9]


In [39]:
arr3[arr3> 2] #elements which is greater than 2

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## question 
##### Create a 3×3 array filled with random numbers and print its shape.
##### Convert an array of floats [1.1, 2.2, 3.3] into integers.
##### Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6].
##### Reshape a 1D array of size 9 into a 3×3 matrix.
##### Use boolean masking to filter numbers greater than 50 in an array.

In [48]:
#1st question
arr5 = np.array([[10,20,30], [40,50,60], [70,80,90]])
print(f"Array with shape -> {arr5.shape} \n and elements are: \n {arr5}")

Array with shape -> (3, 3) 
 and elements are: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]


In [50]:
#question 2
float_arr = np.array([[1.1, 2.2, 3.3]])
print(float_arr.astype(int))

[[1 2 3]]


In [54]:
#question 3
even_arr = np.array([[1, 2, 3, 4, 5, 6]])
print(even_arr[even_arr % 2 == 0])

[2 4 6]


In [56]:
#question 4
oneD = np.array([[1,2,3,4,5,6,7,8,9]])
oneD.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
#question 4
greater_arr = np.array([[344,21,32,4565,67,10,12,]])
greater_arr[greater_arr > 50]

array([ 344, 4565,   67])