In [1]:
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Axis 0 (rows) → Operations move down the columns.
#### Axis 1 (columns) → Operations move across the rows.

In [3]:
print(np.sum(arr, axis = 0)) #summing elements along rows(down columns)
print(np.sum(arr, axis = 1)) # Sum along columns (across each row)

[12 15 18]
[ 6 15 24]


In [4]:
print(arr[0, 1]) #first row second element cause indexing starts from 0

2


#### Indexing in multidimensional arrays

In [5]:
print(arr[0:2, 1:3])  # Extracts first 2 rows and last 2 columns

[[2 3]
 [5 6]]


In [8]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
arr3D.shape # 2 depths(sheets) 2 rows 3 colums

(2, 2, 3)

In [12]:
print(arr3D[0, 1, 2]) # First sheet, second row, third column element

6


In [13]:
print(arr3D[:, 0, :]) #get the first row from both sheets (both sheets, first row, all column)

[[1 2 3]
 [7 8 9]]


In [17]:
print(arr3D[0,0,:]) #only first sheet, first roe, and all columns

[1 2 3]


In [18]:
print(arr3D[0, 0, 0]) #first sheet, first row, first column 

1


In [19]:
# Replace all elements in column 1 with 0
arr[:, 1] = 0
print(arr)



[[1 0 3]
 [4 0 6]
 [7 0 9]]
